version: '3.7'

services:
    ids:
        hostname: 'IDS'
        privileged: true
        container_name : IDS
        build: .
        cap_add : 
            - NET_ADMIN 
        stdin_open: true
        tty: true
        ports:
            - 3000:3000
        volumes:
            - shared-data:/var/log/snort
        networks:
           lan:
             ipv4_address: 192.168.1.2
        command: /bin/bash
        sysctls:
            net.ipv4.conf.all.send_redirects: '0'
            net.ipv4.conf.all.secure_redirects: '0'
            net.ipv4.conf.all.accept_redirects: '0'
            net.ipv4.conf.default.send_redirects: '0'
            net.ipv4.conf.eth0.send_redirects: '0'

    client:
        hostname: 'Client'
        privileged: true
        container_name : Client
        build: .
        cap_add : 
            - NET_ADMIN
        depends_on: 
            - ids
        stdin_open: true
        tty: true
        networks:
           lan:
             ipv4_address: 192.168.1.3
        command: /bin/bash
        sysctls:
            net.ipv4.conf.all.send_redirects: '0'
            net.ipv4.conf.all.secure_redirects: '0'
            net.ipv4.conf.all.accept_redirects: '0'
            net.ipv4.conf.default.send_redirects: '0'
            net.ipv4.conf.eth0.send_redirects: '0'

    wireshark:
        image: lscr.io/linuxserver/wireshark
        container_name: wireshark
        cap_add:
            - NET_ADMIN
        volumes:
            - shared-data:/var/log/snort
        network_mode: service:ids
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Zurich
        #ports:
        #    - 3000:3000
        restart: unless-stopped

volumes:
  shared-data:

networks:
    lan:
        driver: "bridge"
        name: lan
        ipam:
            config:
                - 
                 subnet: 192.168.1.0/24
